apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
  labels:
    app: notes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes-app
        image: yernurqq/notes-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: notes-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: notes-secret
              key: DB_PASS
        - name: APP_USER
          valueFrom:
            configMapKeyRef:
              name: notes-config
              key: APP_USER
        - name: APP_PASS
          valueFrom:
            secretKeyRef:
              name: notes-secret
              key: APP_PASS

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
