apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notes-app
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
