apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
type: Opaque
data:
  DB_USER: "cG9zdGdyZXM="       # echo -n "password" | base64
  DB_PASS: "cGFzc3dvcmQ="
  APP_PASS: "YWRtaW4xMjM="      # echo -n "admin123" | base64
